[package]
name = "adc_imu"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["ad7768-pac"]
[dependencies]
ad7768-pac    = { path = "ad7768-pac" }
defmt         = "1.1.0"
embassy-stm32     = { version = "0.6.0", features = [
    "stm32h753zi",
    "time-driver-any",
    "memory-x",
    "exti",
    "defmt",
] }
embassy-time      = "0.4"
embassy-futures   = "0.1"
embedded-hal-async = "1.0.0"
